api = "0.2"

[buildpack]
  id = "paketo-community/python-runtime"
  name = "Paketo Python Runtime Buildpack"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.8.x"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-13T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "6a6ff81f5a58640a0cbd7fa0493121bb9f1c754def930a69dc54f19a53fc800b"
    source = "https://www.python.org/ftp/python/3.5.9/Python-3.5.9.tgz"
    source_sha256 = "67a1d4fc6e4540d6a092cadc488e533afa961b3c9becc74dc3d6b55cb56e0cc1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.9-linux-x64-cflinuxfs3-6a6ff81f.tgz"
    version = "3.5.9"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-13T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "d806d4eb59186b68991770ba5b12ca05fe341b700c0e33fff2ccf9da96515f55"
    source = "https://www.python.org/ftp/python/3.5.10/Python-3.5.10.tgz"
    source_sha256 = "3496a0daf51913718a6f10e3eda51fa43634cb6151cb096f312d48bdbeff7d3a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.5.10_linux_x64_cflinuxfs3_d806d4eb.tgz"
    version = "3.5.10"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "959ca028a528646a416e0621c1698023832060ce8621fe703cb4549b68e09e22"
    source = "https://www.python.org/ftp/python/3.6.11/Python-3.6.11.tgz"
    source_sha256 = "96621902f89746fffc22f39749c07da7c2917b232e72352e6837d41850f7b90c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.6.11_linux_x64_cflinuxfs3_959ca028.tgz"
    version = "3.6.11"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "73aff787cb1ae9cd7b9d92b3cb3190a863bbdb5a8a913742924e4a57029b1f24"
    source = "https://www.python.org/ftp/python/3.6.12/Python-3.6.12.tgz"
    source_sha256 = "12dddbe52385a0f702fb8071e12dcc6b3cb2dde07cd8db3ed60e90d90ab78693"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.6.12_linux_x64_cflinuxfs3_73aff787.tgz"
    version = "3.6.12"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "e98a931c34bfcc19e36a8fe0807026ad72b638f3ded4da234397439c3d5ead49"
    source = "https://www.python.org/ftp/python/3.7.8/Python-3.7.8.tgz"
    source_sha256 = "0e25835614dc221e3ecea5831b38fa90788b5389b99b675a751414c858789ab0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.7.8_linux_x64_cflinuxfs3_e98a931c.tgz"
    version = "3.7.8"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "14a1d89c6badc6084c4743a166951e33cf13ca7b2fc4d18545da1bd735a77554"
    source = "https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz"
    source_sha256 = "39b018bc7d8a165e59aa827d9ae45c45901739b0bbb13721e4f973f3521c166a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.7.9_linux_x64_cflinuxfs3_14a1d89c.tgz"
    version = "3.7.9"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "08613f978823470ce6b51f284c04bdf7af4b395153dcc49f288e5f6a1bbb75e2"
    source = "https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz"
    source_sha256 = "015115023c382eb6ab83d512762fe3c5502fa0c6c52ffebc4831c4e1a06ffc49"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.5_linux_x64_cflinuxfs3_08613f97.tgz"
    version = "3.8.5"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "8b697568740d53d6db33ec238f9c0ea55b1fe6b80da83b0c04b44a23dc400ecc"
    source = "https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tgz"
    source_sha256 = "313562ee9986dc369cd678011bdfd9800ef62fbf7b1496228a18f86b36428c21"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.6_linux_x64_cflinuxfs3_8b697568.tgz"
    version = "3.8.6"

  [[metadata.dependencies]]
    deprecation_date = "2025-10-05T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "613207fd7a78a8d5b5ee96d9dd07eaf5085e16b5b999bb870c519af30549168f"
    source = "https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz"
    source_sha256 = "df796b2dc8ef085edae2597a41c1c0a63625ebd92487adaef2fed22b567873e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.9.0_linux_x64_cflinuxfs3_613207fd.tgz"
    version = "3.9.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-13T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0478/"
    name = "Python"
    version_line = "3.5.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-23T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0494/"
    name = "Python"
    version_line = "3.6.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.7.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.8.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
