api = "0.2"

[buildpack]
  id = "paketo-community/python-runtime"
  name = "Python Runtime Buildpack"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.8.x"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-13T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "a278e2f47f3c38a785647cc8924f67b2512a7a07b12861b6ad69497e71605782"
    source = "https://www.python.org/ftp/python/3.5.8/Python-3.5.8.tgz"
    source_sha256 = "18c88dfd260147bc7247e6356010e5d4916dfbfc480f6434917f88e61228177a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.8-linux-x64-cflinuxfs3-a278e2f4.tgz"
    version = "3.5.8"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-13T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "6a6ff81f5a58640a0cbd7fa0493121bb9f1c754def930a69dc54f19a53fc800b"
    source = "https://www.python.org/ftp/python/3.5.9/Python-3.5.9.tgz"
    source_sha256 = "67a1d4fc6e4540d6a092cadc488e533afa961b3c9becc74dc3d6b55cb56e0cc1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.9-linux-x64-cflinuxfs3-6a6ff81f.tgz"
    version = "3.5.9"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "3bb086eb29e7385618a23dff6dbff0e7065bd289b5e075db05613046132a4500"
    source = "https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz"
    source_sha256 = "7034dd7cba98d4f94c74f9edd7345bac71c8814c41672c64d9044fa2f96f334d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.10-linux-x64-cflinuxfs3-3bb086eb.tgz"
    version = "3.6.10"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "959ca028a528646a416e0621c1698023832060ce8621fe703cb4549b68e09e22"
    source = "https://www.python.org/ftp/python/3.6.11/Python-3.6.11.tgz"
    source_sha256 = "96621902f89746fffc22f39749c07da7c2917b232e72352e6837d41850f7b90c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.6.11_linux_x64_cflinuxfs3_959ca028.tgz"
    version = "3.6.11"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "50fae53c7c3cdd1a9924e25996fb00ccd870bc145ed74b37d5c470260b602b7c"
    source = "https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz"
    source_sha256 = "8c8be91cd2648a1a0c251f04ea0bb4c2a5570feb9c45eaaa2241c785585b475a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.7-linux-x64-cflinuxfs3-50fae53c.tgz"
    version = "3.7.7"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "e98a931c34bfcc19e36a8fe0807026ad72b638f3ded4da234397439c3d5ead49"
    source = "https://www.python.org/ftp/python/3.7.8/Python-3.7.8.tgz"
    source_sha256 = "0e25835614dc221e3ecea5831b38fa90788b5389b99b675a751414c858789ab0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.7.8_linux_x64_cflinuxfs3_e98a931c.tgz"
    version = "3.7.8"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "de6ad7bf59f0e92513aa69f9c884fa18f7801867f48f2daa8f6552099f833e13"
    source = "https://www.python.org/ftp/python/3.8.4/Python-3.8.4.tgz"
    source_sha256 = "32c4d9817ef11793da4d0d95b3191c4db81d2e45544614e8449255ca9ae3cc18"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.4_linux_x64_cflinuxfs3_de6ad7bf.tgz"
    version = "3.8.4"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "08613f978823470ce6b51f284c04bdf7af4b395153dcc49f288e5f6a1bbb75e2"
    source = "https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz"
    source_sha256 = "015115023c382eb6ab83d512762fe3c5502fa0c6c52ffebc4831c4e1a06ffc49"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.5_linux_x64_cflinuxfs3_08613f97.tgz"
    version = "3.8.5"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-13T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0478/"
    name = "Python"
    version_line = "3.5.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-23T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0494/"
    name = "Python"
    version_line = "3.6.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.7.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.8.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
