api = "0.2"

[buildpack]
  id = "paketo-community/python-runtime"
  name = "Python Runtime Buildpack"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.8.x"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-13T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "a278e2f47f3c38a785647cc8924f67b2512a7a07b12861b6ad69497e71605782"
    source = "https://www.python.org/ftp/python/3.5.8/Python-3.5.8.tgz"
    source_sha256 = "18c88dfd260147bc7247e6356010e5d4916dfbfc480f6434917f88e61228177a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.8-linux-x64-cflinuxfs3-a278e2f4.tgz"
    version = "3.5.8"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-13T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "6a6ff81f5a58640a0cbd7fa0493121bb9f1c754def930a69dc54f19a53fc800b"
    source = "https://www.python.org/ftp/python/3.5.9/Python-3.5.9.tgz"
    source_sha256 = "67a1d4fc6e4540d6a092cadc488e533afa961b3c9becc74dc3d6b55cb56e0cc1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.5.9-linux-x64-cflinuxfs3-6a6ff81f.tgz"
    version = "3.5.9"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "f30bc832807402a93c24d6984182e00575bde327e2e43f00a0a1c5e680ad53b6"
    source = "https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz"
    source_sha256 = "47fc92a1dcb946b9ed0abc311d3767b7215c54e655b17fd1d3f9b538195525aa"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.9-linux-x64-cflinuxfs3-f30bc832.tgz"
    version = "3.6.9"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "3bb086eb29e7385618a23dff6dbff0e7065bd289b5e075db05613046132a4500"
    source = "https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz"
    source_sha256 = "7034dd7cba98d4f94c74f9edd7345bac71c8814c41672c64d9044fa2f96f334d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.10-linux-x64-cflinuxfs3-3bb086eb.tgz"
    version = "3.6.10"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "bb141b1efab045e5374ac583f116f8e37034b6c0b95fd7e9d6e0292a33baafc3"
    source = "https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tgz"
    source_sha256 = "aeee681c235ad336af116f08ab6563361a0c81c537072c1b309d6e4050aa2114"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.6-linux-x64-cflinuxfs3-bb141b1e.tgz"
    version = "3.7.6"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "50fae53c7c3cdd1a9924e25996fb00ccd870bc145ed74b37d5c470260b602b7c"
    source = "https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz"
    source_sha256 = "8c8be91cd2648a1a0c251f04ea0bb4c2a5570feb9c45eaaa2241c785585b475a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.7.7-linux-x64-cflinuxfs3-50fae53c.tgz"
    version = "3.7.7"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "580151dd49bee64fef5dda285a7e7308770d23523a0628580954bdfb3c7ba7df"
    source = "https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz"
    source_sha256 = "e634a7a74776c2b89516b2e013dda1728c89c8149b9863b8cea21946daf9d561"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python-3.8.2-linux-x64-cflinuxfs3-580151dd.tgz"
    version = "3.8.2"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "b4dbe9269f76d37f0ddc8315443e145b1aa9103a64218339d9fcbd3733304e5d"
    source = "https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz"
    source_sha256 = "6af6d4d2e010f9655518d0fc6738c7ff7069f10a4d2fbd55509e467f092a8b90"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.3_linux_x64_cflinuxfs3_b4dbe926.tgz"
    version = "3.8.3"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-13T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0478/"
    name = "Python"
    version_line = "3.5.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-23T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0494/"
    name = "Python"
    version_line = "3.6.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.7.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.8.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
