api = "0.4"

[buildpack]
  id = "paketo-community/cpython"
  name = "Paketo CPython Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.8.x"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "73aff787cb1ae9cd7b9d92b3cb3190a863bbdb5a8a913742924e4a57029b1f24"
    source = "https://www.python.org/ftp/python/3.6.12/Python-3.6.12.tgz"
    source_sha256 = "12dddbe52385a0f702fb8071e12dcc6b3cb2dde07cd8db3ed60e90d90ab78693"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.6.12_linux_x64_cflinuxfs3_73aff787.tgz"
    version = "3.6.12"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "d298666903dbbf6d2782ee43306a64f63561b22d35c563be122b6511fd3f0276"
    source = "https://www.python.org/ftp/python/3.6.13/Python-3.6.13.tgz"
    source_sha256 = "614950d3d54f6e78dac651b49c64cfe2ceefea5af3aff3371a9e4b27a53b2669"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.6.13_linux_x64_cflinuxfs3_d2986669.tgz"
    version = "3.6.13"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "14a1d89c6badc6084c4743a166951e33cf13ca7b2fc4d18545da1bd735a77554"
    source = "https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz"
    source_sha256 = "39b018bc7d8a165e59aa827d9ae45c45901739b0bbb13721e4f973f3521c166a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.7.9_linux_x64_cflinuxfs3_14a1d89c.tgz"
    version = "3.7.9"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "92b2baab95b9374af8b47cc4f9832add6389b9a05edca481f2f2ad69e90f1871"
    source = "https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tgz"
    source_sha256 = "c9649ad84dc3a434c8637df6963100b2e5608697f9ba56d82e3809e4148e0975"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.7.10_linux_x64_cflinuxfs3_92b2baab.tgz"
    version = "3.7.10"

  [[metadata.dependencies]]
    deprecation_date = "2024-10-14T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "4abd87d1817b4cbba1981683891ffafefc2a6fe874d8d00f3348964b0da1c1d6"
    source = "https://www.python.org/ftp/python/3.8.7/Python-3.8.7.tgz"
    source_sha256 = "20e5a04262f0af2eb9c19240d7ec368f385788bba2d8dfba7e74b20bab4d2bac"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.7_linux_x64_cflinuxfs3_4abd87d1.tgz"
    version = "3.8.7"

  [[metadata.dependencies]]
    deprecation_date = "2024-10-14T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "1f37a9d0d4f6e1a267280548a2406ffc07186fb53d148deaff820870eb6a96de"
    source = "https://www.python.org/ftp/python/3.8.8/Python-3.8.8.tgz"
    source_sha256 = "76c0763f048e4f9b861d24da76b7dd5c7a3ba7ec086f40caedeea359263276f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.8.8_linux_x64_cflinuxfs3_1f37a9d0.tgz"
    version = "3.8.8"

  [[metadata.dependencies]]
    deprecation_date = "2025-10-05T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "afdf13b03186c78eaeb1e25238eba77a89ce9b3198225e4caf5ba363552dffd7"
    source = "https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tgz"
    source_sha256 = "29cb91ba038346da0bd9ab84a0a55a845d872c341a4da6879f462e94c741f117"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.9.1_linux_x64_cflinuxfs3_afdf13b0.tgz"
    version = "3.9.1"

  [[metadata.dependencies]]
    deprecation_date = "2025-10-05T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "0702bdd75b9163578d9bb9ce9442ae1f1c370c961d6a2ec040b48ad59a724954"
    source = "https://www.python.org/ftp/python/3.9.2/Python-3.9.2.tgz"
    source_sha256 = "7899e8a6f7946748830d66739f2d8f2b30214dad956e56b9ba216b3de5581519"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/python/python_3.9.2_linux_x64_cflinuxfs3_0702bdd7.tgz"
    version = "3.9.2"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-23T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0494/"
    name = "Python"
    version_line = "3.6.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.7.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-06-27T00:00:00Z
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.8.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
