pull_request_rules:
  - name: Auto merge pull requests from dependabot
    conditions:
      - author=dependabot[bot]
      - status-success=Unit Tests
      - status-success=Integration Tests
    actions:
      merge:
        strict: true
        method: rebase
      delete_head_branch: {}