name: Approve Dependabot PRs

on:
  pull_request:
    branches:
    - master

jobs:
  approve:
    name: Approve PR
    runs-on: ubuntu-latest
    steps:
    - name: Auto-approve Dependabot PRs
      uses: hmarr/auto-approve-action@master
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: {{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
